class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'unzipmirror'
        self.ZipMirrorCommand = 'zipmirror'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.SpeedCommand = 'speedtest'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.CloneCommand = "clone"
        self.WatchCommand = 'watch'
        self.ZipWatchCommand = 'zipwatch'
        self.deleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.SpeedCommand = 'speedtest'
        self.LeechSetCommand = 'leechset'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech'
        self.ZipLeechCommand = 'zipleech'
        self.UnzipLeechCommand = 'unzipleech'

BotCommands = _BotCommands()
